import 'package:flutter/material.dart';
import '../theme.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.background,
      appBar: AppBar(
        title: const Text('Privacy Policy'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Privacy Policy for SMS Manager',
              style: TextStyle(
                fontSize: 24,
                fontWeight: FontWeight.bold,
                color: AppTheme.textPrimary,
              ),
            ),
            const SizedBox(height: 8),
            const Text(
              'Last Updated: July 1, 2026',
              style: TextStyle(
                fontSize: 14,
                color: AppTheme.textSecondary,
              ),
            ),
            const SizedBox(height: 32),
            _buildSection(
              title: '1. Data Collection and Usage',
              content: 'SMS Manager is designed with your privacy as the top priority. The application operates entirely offline. We do not collect, transmit, store on external servers, or share any of your personal information, SMS messages, contacts, or metadata.',
            ),
            const SizedBox(height: 24),
            _buildSection(
              title: '2. Device Permissions',
              content: 'To function correctly, SMS Manager requires the following permissions:\n\n'
                  '• SMS Permission: Required strictly to insert the customized messages into your device\'s local SMS database. We do not read your existing messages for any data collection purposes.\n\n'
                  '• Contacts Permission: Required to allow you to seamlessly select senders or recipients directly from your address book. Your contact list is never uploaded or shared.',
            ),
            const SizedBox(height: 24),
            _buildSection(
              title: '3. Data Storage',
              content: 'All messages generated by this application are saved securely within your device\'s native telephony database. You retain complete ownership and control over this data through your device\'s default messaging application.',
            ),
            const SizedBox(height: 24),
            _buildSection(
              title: '4. Third-Party Services',
              content: 'We do not integrate any third-party analytics, tracking SDKs, or advertising networks. Your usage remains 100% anonymous and localized to your device.',
            ),
            const SizedBox(height: 24),
            _buildSection(
              title: '5. Changes to This Policy',
              content: 'If we ever introduce features that require cloud connectivity or data transmission, we will update this Privacy Policy and explicitly request your consent before doing so. For now, what happens on your device, stays on your device.',
            ),
            const SizedBox(height: 48),
          ],
        ),
      ),
    );
  }

  Widget _buildSection({required String title, required String content}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: const TextStyle(
            fontSize: 18,
            fontWeight: FontWeight.bold,
            color: AppTheme.textPrimary,
          ),
        ),
        const SizedBox(height: 12),
        Text(
          content,
          style: const TextStyle(
            fontSize: 16,
            color: AppTheme.textSecondary,
            height: 1.5,
          ),
        ),
      ],
    );
  }
}
